package com.bennzhang.springcloud.config.configserver;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.config.server.EnableConfigServer;
import org.springframework.util.StringUtils;

@SpringBootApplication
@EnableConfigServer
public class ConfigServerApplication {

	public static void main(String[] args) {
		SpringApplication.run(ConfigServerApplication.class, args);

		String s = "\"id\":id,\n" +
				"\"ACC_NBR\":ACC_NBR,\n" +
				"\"PRODUCT\":PRODUCT,\n" +
				"\"DEALERTYPE\":DEALERTYPE,\n" +
				"\"TERM\":TERM,\n" +
				"\"BOOKVALUE\":BOOKVALUE,\n" +
				"\"ACTIVE\":ACTIVE,\n" +
				"\"PAID\":PAID,\n" +
				"\"PREPAY\":PREPAY,\n" +
				"\"PBD\":PBD,\n" +
				"\"CURRENT\":CURRENT,\n" +
				"\"DQ30\":DQ30,\n" +
				"\"DQ60\":DQ60,\n" +
				"\"DQ90\":DQ90,\n" +
				"\"CHGOFF\":CHGOFF,\n" +
				"\"REPO\":REPO,\n" +
				"\"ACC_CHGOFF_DT\":ACC_CHGOFF_DT,\n" +
				"\"ACC_CHGOFF_AMT\":ACC_CHGOFF_AMT,\n" +
				"\"NETLOSS_TODATE\":NETLOSS_TODATE,\n" +
				"\"DATA_DATE\":DATA_DATE,\n" +
				"\"DLQ_CNT_30\":DLQ_CNT_30,\n" +
				"\"DLQ_CNT_60\":DLQ_CNT_60,\n" +
				"\"DLQ_CNT_90\":DLQ_CNT_90,\n" +
				"\"COLL_BUCKET\":COLL_BUCKET,\n" +
				"\"ACC_STATUS_CD\":ACC_STATUS_CD,\n" +
				"\"DQBAL\":DQBAL,\n" +
				"\"ACTIVEBAL\":ACTIVEBAL,\n" +
				"\"AMT_FIN\":AMT_FIN,\n" +
				"\"ACTIVE_DT\":ACTIVE_DT,\n" +
				"\"CHGOFF_DT\":CHGOFF_DT,\n" +
				"\"CHGOFF_AMT\":CHGOFF_AMT,\n" +
				"\"CHGOFF_AGE\":CHGOFF_AGE,\n" +
				"\"REPO_PAY\":REPO_PAY,\n" +
				"\"AUCTION\":AUCTION,\n" +
				"\"REPO_REC\":REPO_REC,\n" +
				"\"CUSTOMER_PAY\":CUSTOMER_PAY,\n" +
				"\"CUSTOMER_REC\":CUSTOMER_REC,\n" +
				"\"LGBK_PAY\":LGBK_PAY,\n" +
				"\"LGBK_REC\":LGBK_REC,\n" +
				"\"MODELING_SEASONED_OBS\":MODELING_SEASONED_OBS,\n" +
				"\"ACTIVE_DATE\":ACTIVE_DATE,\n" +
				"\"ORIGIN_YEAR\":ORIGIN_YEAR,\n" +
				"\"AMOUNT_FINANCED\":AMOUNT_FINANCED,\n" +
				"\"LTV\":LTV,\n" +
				"\"APR\":APR,\n" +
				"\"DLR_SCORE\":DLR_SCORE,\n" +
				"\"DLR_GRADE\":DLR_GRADE,\n" +
				"\"FICO\":FICO,\n" +
				"\"REGION\":REGION,\n" +
				"\"STATE\":STATE,\n" +
				"\"BOOK_VALUE\":BOOK_VALUE,\n" +
				"\"MILES\":MILES,\n" +
				"\"SEASON\":SEASON,\n" +
				"\"DOWN_PCT\":DOWN_PCT,\n" +
				"\"CASHPRICE\":CASHPRICE,\n" +
				"\"PAYMENT\":PAYMENT,\n" +
				"\"WFSVALUE\":WFSVALUE,\n" +
				"\"BLACKBOOKVALUE\":BLACKBOOKVALUE,\n" +
				"\"COMPARISONBOOK\":COMPARISONBOOK,\n" +
				"\"BOOK_TYPE\":BOOK_TYPE,\n" +
				"\"DIESEL\":DIESEL,\n" +
				"\"VEHICLE_AGE\":VEHICLE_AGE,\n" +
				"\"AUTOCHECKSCORE\":AUTOCHECKSCORE,\n" +
				"\"VEHICLE_MAKE\":VEHICLE_MAKE,\n" +
				"\"DEALER_TYPE\":DEALER_TYPE,\n" +
				"\"DEALSOURCE\":DEALSOURCE,\n" +
				"\"PRIM_INCOMETYPE1\":PRIM_INCOMETYPE1,\n" +
				"\"PRIM_INCOME1\":PRIM_INCOME1,\n" +
				"\"PRIM_INCOMETYPE2\":PRIM_INCOMETYPE2,\n" +
				"\"PRIM_INCOME2\":PRIM_INCOME2,\n" +
				"\"COS_INCOMETYPE1\":COS_INCOMETYPE1,\n" +
				"\"COS_INCOME1\":COS_INCOME1,\n" +
				"\"COS_INCOMETYPE2\":COS_INCOMETYPE2,\n" +
				"\"COS_INCOME2\":COS_INCOME2,\n" +
				"\"COMBINED_INCOME\":COMBINED_INCOME,\n" +
				"\"COMBINED_PTI\":COMBINED_PTI,\n" +
				"\"COMBINED_DTI\":COMBINED_DTI,\n" +
				"\"TOTAL_DEBT\":TOTAL_DEBT,\n" +
				"\"GOOD_COUNT\":GOOD_COUNT,\n" +
				"\"BAD_COUNT\":BAD_COUNT,\n" +
				"\"GTB\":GTB,\n" +
				"\"HGTHB\":HGTHB,\n" +
				"\"HGTAF\":HGTAF,\n" +
				"\"COS_HGTAF\":COS_HGTAF,\n" +
				"\"COS_LOW_INCOME\":COS_LOW_INCOME,\n" +
				"\"HOME_FLAG\":HOME_FLAG,\n" +
				"\"COS_FLAG\":COS_FLAG,\n" +
				"\"WARRANTY_FLAG\":WARRANTY_FLAG,\n" +
				"\"GAP_FLAG\":GAP_FLAG,\n" +
				"\"CUST_FACT\":CUST_FACT,\n" +
				"\"BUREAU_YEARS\":BUREAU_YEARS,\n" +
				"\"RESI_YEARS\":RESI_YEARS,\n" +
				"\"JOB_YEARS\":JOB_YEARS,\n" +
				"\"REPO_COUNT\":REPO_COUNT,\n" +
				"\"BKRP_COUNT\":BKRP_COUNT,\n" +
				"\"PAID_AUTO\":PAID_AUTO,\n" +
				"\"COS_PAIDAUTO\":COS_PAIDAUTO,\n" +
				"\"CLASS_CODE\":CLASS_CODE,\n" +
				"\"CHGOFF_COUNT\":CHGOFF_COUNT,\n" +
				"\"PREV_CHGOFF_AMT\":PREV_CHGOFF_AMT,\n" +
				"\"COLL_COUNT\":COLL_COUNT,\n" +
				"\"COS_HIGHCOLL\":COS_HIGHCOLL,\n" +
				"\"PRIM_PRECISEID\":PRIM_PRECISEID,\n" +
				"\"PRIM_INCOMEINSIGHT\":PRIM_INCOMEINSIGHT,\n" +
				"\"CHARGEOFF_IND_12\":CHARGEOFF_IND_12,\n" +
				"\"CHARGEOFF_IND_15\":CHARGEOFF_IND_15,\n" +
				"\"CHARGEOFF_IND_18\":CHARGEOFF_IND_18,\n" +
				"\"TOTALTRADES\":TOTALTRADES,\n" +
				"\"KOB_AC\":KOB_AC,\n" +
				"\"KOB_AL\":KOB_AL,\n" +
				"\"KOB_AN\":KOB_AN,\n" +
				"\"KOB_AP\":KOB_AP,\n" +
				"\"KOB_AT\":KOB_AT,\n" +
				"\"KOB_AU\":KOB_AU,\n" +
				"\"KOB_AZ\":KOB_AZ,\n" +
				"\"KOB_BB\":KOB_BB,\n" +
				"\"KOB_BC\":KOB_BC,\n" +
				"\"KOB_BI\":KOB_BI,\n" +
				"\"KOB_BM\":KOB_BM,\n" +
				"\"KOB_BS\":KOB_BS,\n" +
				"\"KOB_CG\":KOB_CG,\n" +
				"\"KOB_CS\":KOB_CS,\n" +
				"\"KOB_CZ\":KOB_CZ,\n" +
				"\"KOB_DC\":KOB_DC,\n" +
				"\"KOB_DV\":KOB_DV,\n" +
				"\"KOB_DZ\":KOB_DZ,\n" +
				"\"KOB_EB\":KOB_EB,\n" +
				"\"KOB_EC\":KOB_EC,\n" +
				"\"KOB_EL\":KOB_EL,\n" +
				"\"KOB_ET\":KOB_ET,\n" +
				"\"KOB_EU\":KOB_EU,\n" +
				"\"KOB_EV\":KOB_EV,\n" +
				"\"KOB_EZ\":KOB_EZ,\n" +
				"\"KOB_FA\":KOB_FA,\n" +
				"\"KOB_FB\":KOB_FB,\n" +
				"\"KOB_FC\":KOB_FC,\n" +
				"\"KOB_FF\":KOB_FF,\n" +
				"\"KOB_FI\":KOB_FI,\n" +
				"\"KOB_FL\":KOB_FL,\n" +
				"\"KOB_FM\":KOB_FM,\n" +
				"\"KOB_FP\":KOB_FP,\n" +
				"\"KOB_FR\":KOB_FR,\n" +
				"\"KOB_FS\":KOB_FS,\n" +
				"\"KOB_FU\":KOB_FU,\n" +
				"\"KOB_FW\":KOB_FW,\n" +
				"\"KOB_FY\":KOB_FY,\n" +
				"\"KOB_FZ\":KOB_FZ,\n" +
				"\"KOB_GZ\":KOB_GZ,\n" +
				"\"KOB_HA\":KOB_HA,\n" +
				"\"KOB_HC\":KOB_HC,\n" +
				"\"KOB_HF\":KOB_HF,\n" +
				"\"KOB_HM\":KOB_HM,\n" +
				"\"KOB_HR\":KOB_HR,\n" +
				"\"KOB_HT\":KOB_HT,\n" +
				"\"KOB_HZ\":KOB_HZ,\n" +
				"\"KOB_IL\":KOB_IL,\n" +
				"\"KOB_IZ\":KOB_IZ,\n" +
				"\"KOB_JA\":KOB_JA,\n" +
				"\"KOB_JP\":KOB_JP,\n" +
				"\"KOB_JV\":KOB_JV,\n" +
				"\"KOB_JZ\":KOB_JZ,\n" +
				"\"KOB_KI\":KOB_KI,\n" +
				"\"KOB_KZ\":KOB_KZ,\n" +
				"\"KOB_LA\":KOB_LA,\n" +
				"\"KOB_LP\":KOB_LP,\n" +
				"\"KOB_LZ\":KOB_LZ,\n" +
				"\"KOB_MB\":KOB_MB,\n" +
				"\"KOB_MC\":KOB_MC,\n" +
				"\"KOB_MD\":KOB_MD,\n" +
				"\"KOB_MF\":KOB_MF,\n" +
				"\"KOB_MG\":KOB_MG,\n" +
				"\"KOB_MH\":KOB_MH,\n" +
				"\"KOB_MS\":KOB_MS,\n" +
				"\"KOB_MZ\":KOB_MZ,\n" +
				"\"KOB_NA\":KOB_NA,\n" +
				"\"KOB_ND\":KOB_ND,\n" +
				"\"KOB_NF\":KOB_NF,\n" +
				"\"KOB_NS\":KOB_NS,\n" +
				"\"KOB_NU\":KOB_NU,\n" +
				"\"KOB_NZ\":KOB_NZ,\n" +
				"\"KOB_OC\":KOB_OC,\n" +
				"\"KOB_OZ\":KOB_OZ,\n" +
				"\"KOB_PA\":KOB_PA,\n" +
				"\"KOB_PC\":KOB_PC,\n" +
				"\"KOB_PD\":KOB_PD,\n" +
				"\"KOB_PH\":KOB_PH,\n" +
				"\"KOB_PL\":KOB_PL,\n" +
				"\"KOB_PM\":KOB_PM,\n" +
				"\"KOB_PZ\":KOB_PZ,\n" +
				"\"KOB_QZ\":KOB_QZ,\n" +
				"\"KOB_RA\":KOB_RA,\n" +
				"\"KOB_RC\":KOB_RC,\n" +
				"\"KOB_RD\":KOB_RD,\n" +
				"\"KOB_RE\":KOB_RE,\n" +
				"\"KOB_RH\":KOB_RH,\n" +
				"\"KOB_RR\":KOB_RR,\n" +
				"\"KOB_RZ\":KOB_RZ,\n" +
				"\"KOB_SZ\":KOB_SZ,\n" +
				"\"KOB_TC\":KOB_TC,\n" +
				"\"KOB_TZ\":KOB_TZ,\n" +
				"\"KOB_UA\":KOB_UA,\n" +
				"\"KOB_UC\":KOB_UC,\n" +
				"\"KOB_UD\":KOB_UD,\n" +
				"\"KOB_UE\":KOB_UE,\n" +
				"\"KOB_UF\":KOB_UF,\n" +
				"\"KOB_UG\":KOB_UG,\n" +
				"\"KOB_UL\":KOB_UL,\n" +
				"\"KOB_UO\":KOB_UO,\n" +
				"\"KOB_UP\":KOB_UP,\n" +
				"\"KOB_UT\":KOB_UT,\n" +
				"\"KOB_UW\":KOB_UW,\n" +
				"\"KOB_UZ\":KOB_UZ,\n" +
				"\"KOB_VC\":KOB_VC,\n" +
				"\"KOB_VF\":KOB_VF,\n" +
				"\"KOB_VK\":KOB_VK,\n" +
				"\"KOB_VS\":KOB_VS,\n" +
				"\"KOB_VZ\":KOB_VZ,\n" +
				"\"KOB_WC\":KOB_WC,\n" +
				"\"KOB_WH\":KOB_WH,\n" +
				"\"KOB_WM\":KOB_WM,\n" +
				"\"KOB_WP\":KOB_WP,\n" +
				"\"KOB_WZ\":KOB_WZ,\n" +
				"\"KOB_XM\":KOB_XM,\n" +
				"\"KOB_YA\":KOB_YA,\n" +
				"\"KOB_YB\":KOB_YB,\n" +
				"\"KOB_YC\":KOB_YC,\n" +
				"\"KOB_YD\":KOB_YD,\n" +
				"\"KOB_YF\":KOB_YF,\n" +
				"\"KOB_YL\":KOB_YL,\n" +
				"\"KOB_ZB\":KOB_ZB,\n" +
				"\"KOB_ZC\":KOB_ZC,\n" +
				"\"KOB_ZR\":KOB_ZR,\n" +
				"\"KOB_ZS\":KOB_ZS,\n" +
				"\"KOB_ZT\":KOB_ZT,\n" +
				"\"KOB_ZW\":KOB_ZW,\n" +
				"\"KOB_ZZ\":KOB_ZZ,\n" +
				"\"TCT_AGR\":TCT_AGR,\n" +
				"\"TCT_ATY\":TCT_ATY,\n" +
				"\"TCT_AUL\":TCT_AUL,\n" +
				"\"TCT_AUT\":TCT_AUT,\n" +
				"\"TCT_BCC\":TCT_BCC,\n" +
				"\"TCT_BPG\":TCT_BPG,\n" +
				"\"TCT_BUS\":TCT_BUS,\n" +
				"\"TCT_CC\":TCT_CC,\n" +
				"\"TCT_CM\":TCT_CM,\n" +
				"\"TCT_CS\":TCT_CS,\n" +
				"\"TCT_CEL\":TCT_CEL,\n" +
				"\"TCT_CHG\":TCT_CHG,\n" +
				"\"TCT_CIL\":TCT_CIL,\n" +
				"\"TCT_CLC\":TCT_CLC,\n" +
				"\"TCT_CLS\":TCT_CLS,\n" +
				"\"TCT_COL\":TCT_COL,\n" +
				"\"TCT_CON\":TCT_CON,\n" +
				"\"TCT_CRC\":TCT_CRC,\n" +
				"\"TCT_DC\":TCT_DC,\n" +
				"\"TCT_DEP\":TCT_DEP,\n" +
				"\"TCT_EDU\":TCT_EDU,\n" +
				"\"TCT_FS\":TCT_FS,\n" +
				"\"TCT_FCO\":TCT_FCO,\n" +
				"\"TCT_FHA\":TCT_FHA,\n" +
				"\"TCT_FMH\":TCT_FMH,\n" +
				"\"TCT_GF\":TCT_GF,\n" +
				"\"TCT_GG\":TCT_GG,\n" +
				"\"TCT_GEA\":TCT_GEA,\n" +
				"\"TCT_GFS\":TCT_GFS,\n" +
				"\"TCT_GMD\":TCT_GMD,\n" +
				"\"TCT_GOP\":TCT_GOP,\n" +
				"\"TCT_HO\":TCT_HO,\n" +
				"\"TCT_HE\":TCT_HE,\n" +
				"\"TCT_HI\":TCT_HI,\n" +
				"\"TCT_HHG\":TCT_HHG,\n" +
				"\"TCT_IL\":TCT_IL,\n" +
				"\"TCT_ISC\":TCT_ISC,\n" +
				"\"TCT_LEA\":TCT_LEA,\n" +
				"\"TCT_LPI\":TCT_LPI,\n" +
				"\"TCT_MH\":TCT_MH,\n" +
				"\"TCT_MED\":TCT_MED,\n" +
				"\"TCT_NTE\":TCT_NTE,\n" +
				"\"TCT_PS\":TCT_PS,\n" +
				"\"TCT_PHG\":TCT_PHG,\n" +
				"\"TCT_RC\":TCT_RC,\n" +
				"\"TCT_RE\":TCT_RE,\n" +
				"\"TCT_RF\":TCT_RF,\n" +
				"\"TCT_RO\":TCT_RO,\n" +
				"\"TCT_RS\":TCT_RS,\n" +
				"\"TCT_RV\":TCT_RV,\n" +
				"\"TCT_RCK\":TCT_RCK,\n" +
				"\"TCT_REC\":TCT_REC,\n" +
				"\"TCT_REN\":TCT_REN,\n" +
				"\"TCT_RES\":TCT_RES,\n" +
				"\"TCT_SS\":TCT_SS,\n" +
				"\"TCT_SCC\":TCT_SCC,\n" +
				"\"TCT_SCO\":TCT_SCO,\n" +
				"\"TCT_SDL\":TCT_SDL,\n" +
				"\"TCT_DEC\":TCT_DEC,\n" +
				"\"TCT_SGL\":TCT_SGL,\n" +
				"\"TCT_SHI\":TCT_SHI,\n" +
				"\"TCT_TSL\":TCT_TSL,\n" +
				"\"TCT_UDL\":TCT_UDL,\n" +
				"\"TCT_UGL\":TCT_UGL,\n" +
				"\"TCT_UNK\":TCT_UNK,\n" +
				"\"TCT_UNS\":TCT_UNS,\n" +
				"\"TCT_UTI\":TCT_UTI,\n" +
				"\"TCT_NULL\":TCT_NULL,\n" +
				"\"PST_120_2P_TIMES\":PST_120_2P_TIMES,\n" +
				"\"PST_150_2P_TIMES\":PST_150_2P_TIMES,\n" +
				"\"PST_30_2_TIMES\":PST_30_2_TIMES,\n" +
				"\"PST_30_3_TIMES\":PST_30_3_TIMES,\n" +
				"\"PST_30_4_TIMES\":PST_30_4_TIMES,\n" +
				"\"PST_30_5_TIMES\":PST_30_5_TIMES,\n" +
				"\"PST_30_6P_TIMES\":PST_30_6P_TIMES,\n" +
				"\"PST_30_DAY_DEL\":PST_30_DAY_DEL,\n" +
				"\"PST_30_WAS60\":PST_30_WAS60,\n" +
				"\"PST_60_2_TIMES\":PST_60_2_TIMES,\n" +
				"\"PST_60_3_TIMES\":PST_60_3_TIMES,\n" +
				"\"PST_60_4P_TIMES\":PST_60_4P_TIMES,\n" +
				"\"PST_90_2_TIMES\":PST_90_2_TIMES,\n" +
				"\"PST_90_3P_TIMES\":PST_90_3P_TIMES,\n" +
				"\"PST_90_WAS_120P\":PST_90_WAS_120P,\n" +
				"\"PST_BK_ADJ_PLN\":PST_BK_ADJ_PLN,\n" +
				"\"PST_CHARGEOFF\":PST_CHARGEOFF,\n" +
				"\"PST_CLOSED\":PST_CLOSED,\n" +
				"\"PST_COFF_NOW_PAY\":PST_COFF_NOW_PAY,\n" +
				"\"PST_COLLACCT\":PST_COLLACCT,\n" +
				"\"PST_CRCDLOST\":PST_CRCDLOST,\n" +
				"\"PST_CUR_WAS120\":PST_CUR_WAS120,\n" +
				"\"PST_CUR_WAS150\":PST_CUR_WAS150,\n" +
				"\"PST_CUR_WAS180\":PST_CUR_WAS180,\n" +
				"\"PST_CUR_WAS30\":PST_CUR_WAS30,\n" +
				"\"PST_CUR_WAS_30_2\":PST_CUR_WAS_30_2,\n" +
				"\"PST_CUR_WAS_30_3\":PST_CUR_WAS_30_3,\n" +
				"\"PST_CUR_WAS_30_4\":PST_CUR_WAS_30_4,\n" +
				"\"PST_CUR_WAS_30_5\":PST_CUR_WAS_30_5,\n" +
				"\"PST_CUR_WAS60\":PST_CUR_WAS60,\n" +
				"\"PST_CUR_WAS_60_2\":PST_CUR_WAS_60_2,\n" +
				"\"PST_CUR_WAS_60_3\":PST_CUR_WAS_60_3,\n" +
				"\"PST_CUR_WAS_60_4P\":PST_CUR_WAS_60_4P,\n" +
				"\"PST_CUR_WAS_90\":PST_CUR_WAS_90,\n" +
				"\"PST_CUR_WAS_COL\":PST_CUR_WAS_COL,\n" +
				"\"PST_CUR_WAS_FORE\":PST_CUR_WAS_FORE,\n" +
				"\"PST_CUR_WAS30_6P\":PST_CUR_WAS30_6P,\n" +
				"\"PST_CUR_WAS90_2\":PST_CUR_WAS90_2,\n" +
				"\"PST_CUR_WAS90_3P\":PST_CUR_WAS90_3P,\n" +
				"\"PST_CURR_ACCT\":PST_CURR_ACCT,\n" +
				"\"PST_CURWAS120_2P\":PST_CURWAS120_2P,\n" +
				"\"PST_CURWAS150_2P\":PST_CURWAS150_2P,\n" +
				"\"PST_DECEASED\":PST_DECEASED,\n" +
				"\"PST_DEEDLIEU\":PST_DEEDLIEU,\n" +
				"\"PST_DEL_WAS_120P\":PST_DEL_WAS_120P,\n" +
				"\"PST_DEL_WAS90\":PST_DEL_WAS90,\n" +
				"\"PST_DELINQ120\":PST_DELINQ120,\n" +
				"\"PST_DELINQ150\":PST_DELINQ150,\n" +
				"\"PST_DELINQ180\":PST_DELINQ180,\n" +
				"\"PST_DELINQ60\":PST_DELINQ60,\n" +
				"\"PST_DELINQ90\":PST_DELINQ90,\n" +
				"\"PST_FORECLOS\":PST_FORECLOS,\n" +
				"\"PST_FOREPROC\":PST_FOREPROC,\n" +
				"\"PST_GOVCLAIM\":PST_GOVCLAIM,\n" +
				"\"PST_INSCLAIM\":PST_INSCLAIM,\n" +
				"\"PST_NO_STATUS\":PST_NO_STATUS,\n" +
				"\"PST_PAID\":PST_PAID,\n" +
				"\"PST_PD_BY_DLER\":PST_PD_BY_DLER,\n" +
				"\"PST_PD_CHG_OFF\":PST_PD_CHG_OFF,\n" +
				"\"PST_REDEEMD_REPO\":PST_REDEEMD_REPO,\n" +
				"\"PST_REFINANC\":PST_REFINANC,\n" +
				"\"PST_REPOSSES\":PST_REPOSSES,\n" +
				"\"PST_SCNL\":PST_SCNL,\n" +
				"\"PST_SETTLED\":PST_SETTLED,\n" +
				"\"PST_TRANSFER\":PST_TRANSFER,\n" +
				"\"PST_VOLUSURR\":PST_VOLUSURR,\n" +
				"\"ECOA_ZERO\":ECOA_ZERO,\n" +
				"\"ECOA_ONE\":ECOA_ONE,\n" +
				"\"ECOA_TWO\":ECOA_TWO,\n" +
				"\"ECOA_THREE\":ECOA_THREE,\n" +
				"\"ECOA_FOUR\":ECOA_FOUR,\n" +
				"\"ECOA_FIVE\":ECOA_FIVE,\n" +
				"\"ECOA_SIX\":ECOA_SIX,\n" +
				"\"ECOA_SEVEN\":ECOA_SEVEN,\n" +
				"\"ECOA_A\":ECOA_A,\n" +
				"\"ECOA_B\":ECOA_B,\n" +
				"\"ECOA_C\":ECOA_C,\n" +
				"\"ECOA_D\":ECOA_D,\n" +
				"\"ECOA_E\":ECOA_E,\n" +
				"\"ECOA_G\":ECOA_G,\n" +
				"\"ECOA_H\":ECOA_H,\n" +
				"\"ECOA_X\":ECOA_X,\n" +
				"\"ECOA_NULL\":ECOA_NULL,\n" +
				"\"RIOMC_R\":RIOMC_R,\n" +
				"\"RIOMC_I\":RIOMC_I,\n" +
				"\"AC_03\":AC_03,\n" +
				"\"AC_05\":AC_05,\n" +
				"\"AC_10\":AC_10,\n" +
				"\"AC_21\":AC_21,\n" +
				"\"AC_66\":AC_66,\n" +
				"\"AC_67\":AC_67,\n" +
				"\"AC_68\":AC_68,\n" +
				"\"AC_69\":AC_69,\n" +
				"\"AC_85\":AC_85,\n" +
				"\"AC_87\":AC_87,\n" +
				"\"AC_88\":AC_88,\n" +
				"\"AC_89\":AC_89,\n" +
				"\"AC_91\":AC_91,\n" +
				"\"AC_92\":AC_92,\n" +
				"\"AC_93\":AC_93,\n" +
				"\"AC_94\":AC_94,\n" +
				"\"AC_95\":AC_95,\n" +
				"\"AC_96\":AC_96,\n" +
				"\"AC_97\":AC_97,\n" +
				"\"AC_98\":AC_98,\n" +
				"\"AC_A1\":AC_A1,\n" +
				"\"AC_A2\":AC_A2,\n" +
				"\"AC_A3\":AC_A3,\n" +
				"\"AC_A4\":AC_A4,\n" +
				"\"AC_NULL\":AC_NULL,\n" +
				"\"MR_10LESS\":MR_10LESS,\n" +
				"\"MR_10TO25\":MR_10TO25,\n" +
				"\"MR_25TO50\":MR_25TO50,\n" +
				"\"MR_50TO100\":MR_50TO100,\n" +
				"\"PASTDUE_NOTZERO\":PASTDUE_NOTZERO,\n" +
				"\"TOT_PASTDUEAMOUNT\":TOT_PASTDUEAMOUNT,\n" +
				"\"MAX_PASTDUEAMOUNT\":MAX_PASTDUEAMOUNT,\n" +
				"\"MIN_PASTDUEAMOUNT\":MIN_PASTDUEAMOUNT,\n" +
				"\"AVG_PASTDUEAMOUNT\":AVG_PASTDUEAMOUNT,\n" +
				"\"TOT_BALANCEAMOUNT\":TOT_BALANCEAMOUNT,\n" +
				"\"MAX_BALANCEAMOUNT\":MAX_BALANCEAMOUNT,\n" +
				"\"MIN_BALANCEAMOUNT\":MIN_BALANCEAMOUNT,\n" +
				"\"AVG_BALANCEAMOUNT\":AVG_BALANCEAMOUNT,\n" +
				"\"TOT_ORIGINALBALANCE\":TOT_ORIGINALBALANCE,\n" +
				"\"MAX_ORIGINALBALANCE\":MAX_ORIGINALBALANCE,\n" +
				"\"MIN_ORIGINALBALANCE\":MIN_ORIGINALBALANCE,\n" +
				"\"AVG_ORIGINALBALANCE\":AVG_ORIGINALBALANCE,\n" +
				"\"TOT_MONTHLYPAYMENTAMOUNT\":TOT_MONTHLYPAYMENTAMOUNT,\n" +
				"\"MAX_MONTHLYPAYMENTAMOUNT\":MAX_MONTHLYPAYMENTAMOUNT,\n" +
				"\"MIN_MONTHLYPAYMENTAMOUNT\":MIN_MONTHLYPAYMENTAMOUNT,\n" +
				"\"AVG_MONTHLYPAYMENTAMOUNT\":AVG_MONTHLYPAYMENTAMOUNT,\n" +
				"\"ECOA_ZERO_PR\":ECOA_ZERO_PR,\n" +
				"\"ECOA_ONE_PR\":ECOA_ONE_PR,\n" +
				"\"ECOA_TWO_PR\":ECOA_TWO_PR,\n" +
				"\"ECOA_NULL_PR\":ECOA_NULL_PR,\n" +
				"\"RT_00\":RT_00,\n" +
				"\"RT_01\":RT_01,\n" +
				"\"RT_08\":RT_08,\n" +
				"\"RT_09\":RT_09,\n" +
				"\"RT_13\":RT_13,\n" +
				"\"RT_15\":RT_15,\n" +
				"\"RT_16\":RT_16,\n" +
				"\"RT_17\":RT_17,\n" +
				"\"RT_22\":RT_22,\n" +
				"\"RT_23\":RT_23,\n" +
				"\"RT_24\":RT_24,\n" +
				"\"RT_27\":RT_27,\n" +
				"\"RT_29\":RT_29,\n" +
				"\"RT_30\":RT_30,\n" +
				"\"RT_31\":RT_31,\n" +
				"\"RT_32\":RT_32,\n" +
				"\"RT_33\":RT_33,\n" +
				"\"MAX_AMOUNT_PR\":MAX_AMOUNT_PR,\n" +
				"\"MIN_AMOUNT_PR\":MIN_AMOUNT_PR,\n" +
				"\"AVG_AMOUNT_PR\":AVG_AMOUNT_PR,\n" +
				"\"TOT_AMOUNT_PR\":TOT_AMOUNT_PR\n"

	}
}
